#!/bin/sh

bash ./schema-uninstall

rm "/usr/local/bin/ipmonitor-gtk"

rm "/usr/share/icons/hicolor/16x16/apps/ipmonitor-gtk.png"
rm "/usr/share/icons/hicolor/48x48/apps/ipmonitor-gtk.png"
rm "/usr/share/icons/hicolor/scalable/apps/ipmonitor-gtk.svg"

# NB: user-specific  ~/.local/share/applications has been a flop for me
rm "/usr/share/applications/uk.co.archaicgroves.ipmonitor-gtk.desktop"
gtk-update-icon-cache /usr/share/icons/hicolor/
